# yaml-language-server: $schema=../../src/asqi/schemas/asqi_systems_config.schema.json
systems:
  azure-gpt-4o-mini:
    type: "llm_api"
    params:
      model: "azure/gpt-4o-mini"
      api_key: "sk-1234"
      base_url: "http://localhost:4000/v1"
      env_file: ".env"

  custom_rag_chatbot:
    type: "rag_api"
    description: "Custom RAG Chatbot"
    params:
      base_url: "http://localhost:4000/v1" # Assuming that the test RAG API chatbot is configured via litellm in asqi-chatbots-demo repo
      model: "custom_rag_chatbot"
      api_key: "sk-1234"
      env_file: ".env"